apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      containers:
        - name: bookstack
          image: linuxserver/bookstack:latest
          env:
            - name: APP_URL
              value: bookstack.test.com
            - name: DB_HOST
              value: mysql-service
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: bookstack
            - name: DB_USER
              value: db_user
            - name: DB_PASS
              value: password
